sdm660-common: Downgrade qti-telephony-common to LA.UM.8.2.r1-05100-sdm660.0
In some ROM's this causes the issue below:

java.lang.NoSuchMethodError: No virtual method getEssentialRecordsLoaded()Z in class Lcom/android/internal/telephony/uicc/IccRecords; or its super classes (declaration of 'com.android.internal.telephony.uicc.IccRecords' appears in /system/framework/telephony-common.jar)